import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pinisi_parking_spot/bloc/page_bloc.dart';
import 'package:pinisi_parking_spot/config/size_config.dart';
import 'package:shared_preferences/shared_preferences.dart';
part 'get_colors.dart';
part 'get_theme.dart';
part 'get_shared_preferences.dart';
part 'shared_value.dart';
